language: node_js
node_js: node
env:
  - PROJECT=client
  - PROJECT=server
install:
  - cd $PROJECT
  - npm install
script: NODE_ENV=production npm run build
before_deploy: mv .gitignore-deploy .gitignore
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
    condition: "$PROJECT = client"
  local-dir: client
  verbose: true