language: node_js
node_js: node
services:
  - mongodb
env:
  - PROJECT=client
  - PROJECT=server
install:
  - cd $PROJECT
  - npm install
before_script:
  - sleep 3 # Give Mongo some time to initialize. https://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo qocdb-test --eval 'db.createUser({ user:"travis", pwd:"test", roles:["readWrite"] });' # TODO: get user/pwd from env vars
script:
  - NODE_ENV=production npm run build
  - npm test
before_deploy: mv .gitignore-deploy .gitignore || true # suppress error silently
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: deploy
      condition: $PROJECT = client
    local-dir: client
    verbose: true
  - provider: heroku
    api_key: "$HEROKU_API_KEY"
    app: qoc
    on:
      branch: deploy
      condition: $PROJECT = server
      # run: npm run db:migrate