language: node_js
node_js: node
env:
  - PROJECT=client
  - PROJECT=server
install: cd $PROJECT && npm install
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  keep-history: false
  on:
    branch: master
  local-dir: client