language: node_js
node_js: node
env:
  - PROJECT=client
  - PROJECT=server
install: cd $PROJECT && npm install
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
    condition: "$PROJECT = client"
  local-dir: client