language: node_js
node_js: node
env:
  - PROJECT=client
  - PROJECT=server
install: cd $PROJECT && npm install
script: npm run build
before_deploy:
  - pwd
  - rm -rf .gitignore node_modules
deploy:
  provider: pages
  skip-cleanup: true
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
    condition: "$PROJECT = client"
  local-dir: client
  verbose: true